site_name: librephone
site_description: Free the phone!
# strict: true
# site_url: "https:fsf.org"

repo_name: "librephone"
repo_url: "https://codeberg.org/rsavoye/librephone.git"
edit_uri: "edit/main/docs/"

extra:
  copyright: Copyright &copy; 2025 FSF
  generator: false

theme:
  name: material
  palette:
    primary: custom
  favicon: assets/favicon.ico
  logo: campaigns_gnu.small.png
  # custom_dir: docs/overrides

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

nav:
  - Home: index.md
  - Get Started:
    - License: LICENSE.md
    - The Utilities: utilities.md
    - Flashing HOWTO: flashing.md
  - Lineage Packages:
    - File Structure: files.md
    - Comparing Devices: comparing.md
  - Utilities:
    - Extracting Metadata: extractor.md
    - Importing file metadata: import-device.md
    - Querying the Database: query-device.md
    - Processing Everything: images_util.md
    - Generating Code Bindings:
      - Generating the Files: generator.md
      - Code Stub Syntax: stubs.md
    - Admin Script: images_util.md
  - Tech Details:
    - Tools: tools.md
    - Disassembling Thumb: thumb.md
    - Sample Data Extracts: csvdata.md
    - The ATH11k Driver: ath11k.md
    - Wireless Processor SubSystem:
      - Wireless: wireless.md
      - wpss.b01: wpss.b01.md
      - wpss.b02: wpss.b02.md
      - wpss.b03: wpss.b03.md
      - wpss.b04: wpss.b04.md
      - wpss.b05: wpss.b05.md
      - wpss.b06: wpss.b06.md
      - wpss.b07: wpss.b07.md
      - wpss.b08: wpss.b08.md
      - wpss.b09: wpss.b09.md
      - wpss.b10: wpss.b10.md
      # - wpss.b11: wpss.b11.md
      # - wpss.b12: wpss.b12.md
    - Other Firmware: other.md
